language: node_js

node_js:
- 6

addons:
  firefox: 49.0.1

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

install:
- npm install
- npm dedupe

script: npm run dist