name: build

on: [push, workflow_dispatch]

permissions:
  contents: write
  id-token: write

jobs:
  build:
    uses: datavisyn/github-workflows/.github/workflows/build-node.yml@main
    secrets: inherit 
